version: '3.9'
services:
  backend:    
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: 'bitnami/mariadb:10.3'
    ports:
      - 3306:3306
    volumes:
      - 'mariadb_data:/warmup_mariadb_data/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=ambassador
      - MARIADB_USER=user
      - MARIADB_PASSWORD=user

volumes:
  mariadb_data:
    driver: local
